services:
  app_proxy:
    environment:
      APP_HOST: lares_web_1
      APP_PORT: 8000

  web:
    image: lares:0.1.0
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/app/backend/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
